export type ErrorBody<CodeList = string> = {
  code: CodeList;
  message: string;
}

export type PaymentInquiryErrorCode =
  | "UNAUTHORIZED_KEY"
  | "FORBIDDEN_CONSECUTIVE_REQUEST"
  | "INCORRECT_BASIC_AUTH_FORMAT"
  | "NOT_FOUND_PAYMENT"
  | "NOT_FOUND"
  | "FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING";

export type PaymentConfirmErrorCode =
  | "ALREADY_PROCESSED_PAYMENT"
  | "PROVIDER_ERROR"
  | "EXCEED_MAX_CARD_INSTALLMENT_PLAN"
  | "INVALID_REQUEST"
  | "NOT_ALLOWED_POINT_USE"
  | "INVALID_API_KEY"
  | "INVALID_REJECT_CARD"
  | "BELOW_MINIMUM_AMOUNT"
  | "INVALID_CARD_EXPIRATION"
  | "INVALID_STOPPED_CARD"
  | "EXCEED_MAX_DAILY_PAYMENT_COUNT"
  | "NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT"
  | "INVALID_CARD_INSTALLMENT_PLAN"
  | "NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN"
  | "EXCEED_MAX_PAYMENT_AMOUNT"
  | "NOT_FOUND_TERMINAL_ID"
  | "INVALID_AUTHORIZE_AUTH"
  | "INVALID_CARD_LOST_OR_STOLEN"
  | "RESTRICTED_TRANSFER_ACCOUNT"
  | "INVALID_CARD_NUMBER"
  | "INVALID_UNREGISTERED_SUBMALL"
  | "NOT_REGISTERED_BUSINESS"
  | "EXCEED_MAX_ONE_DAY_WITHDRAW_AMOUNT"
  | "EXCEED_MAX_ONE_TIME_WITHDRAW_AMOUNT"
  | "CARD_PROCESSING_ERROR"
  | "EXCEED_MAX_AMOUNT"
  | "INVALID_ACCOUNT_INFO_RE_REGISTER"
  | "NOT_AVAILABLE_PAYMENT"
  | "UNAPPROVED_ORDER_ID"
  | "UNAUTHORIZED_KEY"
  | "REJECT_ACCOUNT_PAYMENT"
  | "REJECT_CARD_PAYMENT"
  | "REJECT_CARD_COMPANY"
  | "FORBIDDEN_REQUEST"
  | "REJECT_TOSSPAY_INVALID_ACCOUNT"
  | "EXCEED_MAX_AUTH_COUNT"
  | "EXCEED_MAX_ONE_DAY_AMOUNT"
  | "NOT_AVAILABLE_BANK"
  | "INVALID_PASSWORD"
  | "INCORRECT_BASIC_AUTH_FORMAT"
  | "FDS_ERROR"
  | "NOT_FOUND_PAYMENT"
  | "NOT_FOUND_PAYMENT_SESSION"
  | "FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING"
  | "FAILED_INTERNAL_SYSTEM_PROCESSING"
  | "UNKNOWN_PAYMENT_ERROR";

export type PaymentCancelErrorCode =
  | 'ALREADY_CANCELED_PAYMENT'
  | 'INVALID_REFUND_ACCOUNT_INFO'
  | 'EXCEED_CANCEL_AMOUNT_DISCOUNT_AMOUNT'
  | 'INVALID_REQUEST'
  | 'INVALID_REFUND_ACCOUNT_NUMBER'
  | 'INVALID_BANK'
  | 'NOT_MATCHES_REFUNDABLE_AMOUNT'
  | 'PROVIDER_ERROR'
  | 'REFUND_REJECTED'
  | 'ALREADY_REFUND_PAYMENT'
  | 'UNAUTHORIZED_KEY'
  | 'NOT_CANCELABLE_AMOUNT'
  | 'FORBIDDEN_CONSECUTIVE_REQUEST'
  | 'FORBIDDEN_REQUEST'
  | 'NOT_CANCELABLE_PAYMENT'
  | 'EXCEED_MAX_REFUND_DUE'
  | 'NOT_ALLOWED_PARTIAL_REFUND_WAITING_DEPOSIT'
  | 'NOT_ALLOWED_PARTIAL_REFUND'
  | 'NOT_AVAILABLE_BANK'
  | 'INCORRECT_BASIC_AUTH_FORMAT'
  | 'NOTCANCELABLE_PAYMENT_FOR_DORMANT_USER'
  | 'NOT_FOUND_PAYMENT'
  | 'FAILED_INTERNAL_SYSTEM_PROCESSING'
  | 'FAILED_REFUND_PROCESS'
  | 'FAILED_METHOD_HANDLING_CANCEL'
  | 'FAILED_PARTIAL_REFUND'
  | 'COMMON_ERROR'
  | 'FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING';

export type PaymentKeyInErrorCode =
  | 'INVALID_CARD_EXPIRATION'
  | 'INVALID_CARD_NUMBER'
  | 'INVALID_CARD_PASSWORD'
  | 'INVALID_CARD_IDENTITY'
  | 'INVALID_STOPPED_CARD'
  | 'INVALID_REJECT_CARD'
  | 'INVALID_BIRTH_DAY_FORMAT'
  | 'NOT_SUPPORTED_CARD_TYPE'
  | 'NOT_REGISTERED_CARD_COMPANY'
  | 'INVALID_REQUEST'
  | 'NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN'
  | 'INVALID_CARD_INSTALLMENT_PLAN'
  | 'NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT'
  | 'INVALID_EMAIL'
  | 'BELOW_MINIMUM_AMOUNT'
  | 'DUPLICATED_ORDER_ID'
  | 'INVALID_ORDER_ID'
  | 'NOT_ALLOWED_POINT_USE'
  | 'UNAUTHORIZED_KEY'
  | 'REJECT_CARD_PAYMENT'
  | 'EXCEED_MAX_AUTH_COUNT'
  | 'REJECT_ACCOUNT_PAYMENT'
  | 'REJECT_CARD_COMPANY'
  | 'INCORRECT_BASIC_AUTH_FORMAT'
  | 'FAILED_INTERNAL_SYSTEM_PROCESSING'
  | 'FAILED_DB_PROCESSING'
  | 'FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING'
  | 'FAILED_CARD_COMPANY_RESPONSE';

export type IssueVirtualAccountErrorCode =
  | 'DUPLICATED_ORDER_ID'
  | 'INVALID_REQUEST'
  | 'INVALID_REGISTRATION_NUMBER_TYPE'
  | 'INVALID_DATE'
  | 'INVALID_BANK'
  | 'EXCEED_MAX_DUE_DATE'
  | 'UNAUTHORIZED_KEY'
  | 'INCORRECT_BASIC_AUTH_FORMAT'
  | 'FAILED_INTERNAL_SYSTEM_PROCESSING'
  | 'FAILED_DB_PROCESSING';

export type IssueBillingKeyErrorCode =
  | "INVALID_CARD_NUMBER"
  | "NOT_SUPPORTED_CARD_TYPE"
  | "INVALID_CARD_PASSWORD"
  | "INVALID_CARD_EXPIRATION"
  | "INVALID_CARD_IDENTITY"
  | "INVALID_REJECT_CARD"
  | "INVALID_STOPPED_CARD"
  | "INVALID_BIRTH_DAY_FORMAT"
  | "NOT_REGISTERED_CARD_COMPANY"
  | "INVALID_EMAIL"
  | "NOT_SUPPORTED_METHOD"
  | "INVALID_REQUEST"
  | "EXCEED_MAX_AUTH_COUNT"
  | "REJECT_CARD_COMPANY"
  | "REJECT_ACCOUNT_PAYMENT"
  | "COMMON_ERROR";

export type BillingConfirmErrorCode =
  | 'INVALID_STOPPED_CARD'
  | 'INVALID_REJECT_CARD'
  | 'INVALID_CARD_EXPIRATION'
  | 'INVALID_CARD_NUMBER'
  | 'INVALID_BILL_KEY_REQUEST'
  | 'NOT_SUPPORTED_CARD_TYPE'
  | 'DUPLICATED_ORDER_ID'
  | 'NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT'
  | 'INVALID_CARD_INSTALLMENT_PLAN'
  | 'NOT_MATCHES_CUSTOMER_KEY'
  | 'INVALID_REQUEST'
  | 'BELOW_MINIMUM_AMOUNT'
  | 'NOT_REGISTERED_CARD_COMPANY'
  | 'NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN'
  | 'UNAUTHORIZED_KEY'
  | 'REJECT_CARD_PAYMENT'
  | 'REJECT_ACCOUNT_PAYMENT'
  | 'REJECT_CARD_COMPANY'
  | 'EXCEED_MAX_AUTH_COUNT'
  | 'INCORRECT_BASIC_AUTH_FORMAT'
  | 'FAILED_INTERNAL_SYSTEM_PROCESSING'
  | 'FAILED_DB_PROCESSING'
  | 'FAILED_CARD_COMPANY_RESPONSE';

export type TransactionInquiryErrorCode = 'INVALID_DATE'
  | 'INVALID_TRANSACTION_KEY'
  | 'UNAUTHORIZED_KEY'
  | 'INCORRECT_BASIC_AUTH_FORMAT';

export type SettlementInquiryErrorCode = 'INVALID_DATE'
  | 'INVALID_REQUEST'
  | 'UNAUTHORIZED_KEY'
  | 'INCORRECT_BASIC_AUTH_FORMAT'
  | 'COMMON_ERROR';

export type SettlementManuallyErrorCode = 'INVALID_REQUEST'
  | 'FORBIDDEN_REQUEST'
  | 'NOT_FOUND_PAYMENT'
  | 'NOT_FOUND'
  | 'NOT_FOUND_METHOD';

export type CashReceiptCancelErrorCode = 'FORBIDDEN_REQUEST'
  | 'NOT_FOUND_RECEIPT'
  | 'FAILED_INTERNAL_SYSTEM_PROCESSING';

export type CashReceiptInquiryErrorCode = 'API_VERSION_UPDATE_NEEDED'
  | 'INVALID_BUSINESS_NUMBER'
  | 'INVALID_REQUIRED_PARAM'
  | 'UNAUTHORIZED_KEY'
  | 'INCORRECT_BASIC_AUTH_FORMAT';
